/* generated by precalc.print_sql_indexes() */
ALTER TABLE icd_authorcategorymetrics
ADD INDEX index_pos_twopi_changes (instance, author_id, x_twopi, y_twopi, changes, category_id),
ADD INDEX index_pos_twopi_annotations (instance, author_id, x_twopi, y_twopi, annotations, category_id),
ADD INDEX index_pos_twopi_activity (instance, author_id, x_twopi, y_twopi, activity, category_id),
ADD INDEX index_pos_twopi_acc_changes (instance, author_id, x_twopi, y_twopi, acc_changes, category_id),
ADD INDEX index_pos_twopi_acc_annotations (instance, author_id, x_twopi, y_twopi, acc_annotations, category_id),
ADD INDEX index_pos_twopi_acc_activity (instance, author_id, x_twopi, y_twopi, acc_activity, category_id),
ADD INDEX index_pos_sfdp_changes (instance, author_id, x_sfdp, y_sfdp, changes, category_id),
ADD INDEX index_pos_sfdp_annotations (instance, author_id, x_sfdp, y_sfdp, annotations, category_id),
ADD INDEX index_pos_sfdp_activity (instance, author_id, x_sfdp, y_sfdp, activity, category_id),
ADD INDEX index_pos_sfdp_acc_changes (instance, author_id, x_sfdp, y_sfdp, acc_changes, category_id),
ADD INDEX index_pos_sfdp_acc_annotations (instance, author_id, x_sfdp, y_sfdp, acc_annotations, category_id),
ADD INDEX index_pos_sfdp_acc_activity (instance, author_id, x_sfdp, y_sfdp, acc_activity, category_id);